version: '3'
services:
  env:
    build:
      context: ./containers/env
      args:
        - LAB_USER=$LAB_USER
        - LAB_UID=$LAB_UID
        - LAB_GID=$LAB_GID
        - LAB_GROUP=$LAB_GROUP
  jupyter:
    build: ./containers/jupyter
    ports:
      - '8888:8888'
    volumes:
      - $DATASET_PATH:/home/jovyan/dataset
      - ./workspace/.ssh:/home/jovyan/.ssh
      - ./workspace/notebooks:/home/jovyan/notebooks
      - ./workspace/resources:/home/jovyan/resources
      - ./workspace/develop:/home/jovyan/develop
    environment:
      - grant_sudo=yes
      - HOST_USER_ID=$HOST_USER_ID
      - HOST_GROUP_ID=$HOST_GROUP_ID
      - NB_UID=$HOST_USER_ID
      - NB_GID=$HOST_GROUP_ID
    user: root
