version: '3'
services:
  core:
    image: atbell013/mylab_core
  env:
    build:
      context: ./containers/env
      args:
        - LAB_USER=$LAB_USER
        - LAB_UID=$LAB_UID
    depends_on:
      - core
  jupyter:
    build:
      context: ./containers/jupyter
      args:
        - JUPYTER_PASS=$JUPYTER_PASS
    ports:
      - '8888:8888'
    volumes:
      - ./workspace/.ssh:/home/$LAB_USER/.ssh
      - ./workspace/notebooks:/home/$LAB_USER/notebooks
      - ./workspace/resources:/home/$LAB_USER/resources
      - ./workspace/develop:/home/$LAB_USER/develop
    environment:
      - grant_sudo=yes
      - LAB_USER=$LAB_USER
      - LAB_UID=$LAB_UID
      - LAB_GROUP="lab_member"
      - LAB_GID=111
    depends_on:
      - env
    user: root
