version: '3'
services:
  core:
    image: atbell013/mylab_core
  env:
    build:
      context: ./containers/env
      args:
        - LAB_USER=$LAB_USER
        - LAB_UID=$LAB_UID
        - ROOT_PASSWORD=$ROOT_PASSWORD
        - LAB_USER_PASSWORD=$LAB_USER_PASSWORD
    depends_on:
      - core
  jupyter:
    build:
      context: ./containers/jupyter
      args:
        - JUPYTER_PASS=$JUPYTER_PASS
    ports:
      - '8888:8888'
    volumes:
      - ./workspace/.kaggle:/home/$LAB_USER/.kaggle
      - ./workspace/.ssh:/home/$LAB_USER/.ssh
      - ./workspace/notebooks:/home/$LAB_USER/notebooks
      - ./workspace/resources:/home/$LAB_USER/resources
      - ./workspace/develop:/home/$LAB_USER/develop
    environment:
      - grant_sudo=yes
      - LAB_USER=$LAB_USER
      - LAB_UID=$LAB_UID
      - LAB_GROUP="lab_member"
      - LAB_GID=111
    depends_on:
      - env
    user: root

  jupyter-spark:
    build:
      context: ./containers/jupyter_spark
      args:
        - JUPYTER_PASS=$JUPYTER_PASS
    ports:
      - '8889:8889'
    volumes:
      - ./workspace/.kaggle:/home/$LAB_USER/.kaggle
      - ./workspace/.ssh:/home/$LAB_USER/.ssh
      - ./workspace/notebooks:/home/$LAB_USER/notebooks
      - ./workspace/resources:/home/$LAB_USER/resources
      - ./workspace/develop:/home/$LAB_USER/develop
    environment:
      - grant_sudo=yes
      - LAB_USER=$LAB_USER
      - LAB_UID=$LAB_UID
      - LAB_GROUP="lab_member"
      - LAB_GID=111
    depends_on:
      - env
      - master
    user: root

  master:
    image: mylab_env
    # build:
    #   context: ./containers/spark
    command: /home/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./workspace/spark/data:/tmp/data
    links:
      - worker1
      - worker2

  worker1:
    image: mylab_env
    build:
      context: ./containers/spark
    command: /home/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    volumes:
      - ./workspace/spark/data:/tmp/data

  worker2:
    image: mylab_env
    build:
      context: ./containers/spark
    command: /home/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8082:8082
    volumes:
      - ./workspace/spark/data:/tmp/data
