version: '2'
services:
  ssh_server:
    build: ./containers/ssh_server
    ports:
      - '8889:22'
    volumes:
      - $DATASET_PATH:/home/jovyan/dataset
      - ./workspace/.ssh:/home/jovyan/.ssh
      - ./workspace/notebooks:/home/jovyan/notebooks
      - ./workspace/resources:/home/jovyan/resources
      - ./workspace/develop:/home/jovyan/develop
    environment:
      - grant_sudo=yes
    user: root
    tty: true
  jupyter:
    build: ./containers/jupyter
    ports:
      - '8888:8888'
    volumes:
      - $DATASET_PATH:/home/jovyan/dataset
      - ./workspace/.ssh:/home/jovyan/.ssh
      - ./workspace/notebooks:/home/jovyan/notebooks
      - ./workspace/resources:/home/jovyan/resources
      - ./workspace/develop:/home/jovyan/develop
    environment:
      - grant_sudo=yes
    user: root
